name: github-H100

on:
  pull_request:
    paths-ignore:
    - '**/*.rst'
    - '**/*.md'
    - '**/requirements.txt'
    - '**/*.py'
    - 'docs/**'
    types: [ opened, reopened, synchronize ]

permissions:
  contents: none

# Cancels any in progress 'workflow' associated with this PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  skxci:
    # TODO: allow re-run via retest label if: ${{ github.event.label.name == 'AT: RETEST' }}
    name: h100-ci
    runs-on: [h100]

    steps:
      - name: checkout_kokkos_kernels
        uses: actions/checkout@v3
        with:
          path: kokkos-kernels

      - name: checkout_kokkos
        uses: actions/checkout@v3
        with:
          repository: kokkos/kokkos
          ref: ${{ github.base_ref }}
          path: kokkos

      - name: PR_H100_CUDA1180_CONFIGURE
        run: |
          eval $MODULEENV
          module load cmake gcc/11.3.0 cuda/11.8.0 git openblas/0.3.23
          $PWD/kokkos-kernels/cm_generate_makefile.bash --with-cuda --arch=HOPPER90 --compiler=$PWD/kokkos/bin/nvcc_wrapper -kokkos-path=$PWD/kokkos --with-tpls=cusparse,cublas

      - name: PR_H100_CUDA1180_BUILD
        run: |
          eval $MODULEENV
          module load cmake gcc/11.3.0 cuda/11.8.0 git openblas/0.3.23
          make -j16

      - name: PR_H100_CUDA1180_TEST
        run: |
          eval $MODULEENV
          module load cmake gcc/11.3.0 cuda/11.8.0 git openblas/0.3.23
          ctest --output-on-failure
