name: github-SKX

on:
  pull_request:
    paths-ignore:
    - '**/*.rst'
    - '**/*.md'
    - '**/requirements.txt'
    - '**/*.py'
    - 'docs/**'
    types: [ opened, reopened, synchronize ]

permissions:
  contents: none

# Cancels any in progress 'workflow' associated with this PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  skxci:
    # TODO: allow re-run via retest label if: ${{ github.event.label.name == 'AT: RETEST' }}
    name: skx-ci
    runs-on: [skx]

    steps:
      - name: checkout_kokkos_kernels
        uses: actions/checkout@v3
        with:
          path: kokkos-kernels

      - name: checkout_kokkos
        uses: actions/checkout@v3
        with:
          repository: kokkos/kokkos
          ref: ${{ github.base_ref }}
          path: kokkos

      - name: PR_SKX_CLANG1001_THREADS_SERIAL_LEFT_RELEASE
        run: |
          kokkos-kernels/scripts/cm_test_all_sandia \
            --spot-check llvm/10.0.1 \
            --kokkos-path=$PWD/kokkos \
            --kokkoskernels-path=$PWD/kokkos-kernels \
            --cxxstandard=17
